name: CI
on:
  push:
  schedule:
    - cron: '*/5 * * * *'
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run:  ping -c 4 mirrors.huaweicloud.com
      - name: Run a multi-line script
        run:  ping -c 4 developer.aliyun.com
      - name: Run a multi-line script
        run:  ping -c 4 mirrors.tuna.tsinghua.edu.cn
      - name: Run a multi-line script
        run:  ping -c 4 mirrors.ustc.edu.cn
        
          
         
