name: CI
on:
  push:
  schedule:
    - cron: '*/5 * * * *'
env:
  TZ: Asia/Shanghai
jobs:
  build:
      runs-on: windows-latest
      steps:
        - name: ping
          run: ping nodejs.org
#           run: ping mirrors.huaweicloud.com
        - name: Run a multi-line script
          run: ping developer.aliyun.com
        - name: Run a multi-line script
          run: ping mirrors.tuna.tsinghua.edu.cn
        - name: Run a multi-line script
          run: ping mirrors.ustc.edu.cn
