name: Git Mirror Action
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: 'main'
          persist-credentials: false
          fetch-depth: 0
        env:
          TZ: Asia/Shanghai
      - run: |
          date > generated.txt
          git remote add gitee https://gitee.com/qcyblm/hexo.git
          git fetch -q --all
          git push -q https://qcyblm:${{ secrets.GITEE_TOKEN }}@gitee.com/$GITHUB_REPOSITORY.git main
